### ISSUE TITLE
推荐添加一些注释

### ISSUE THREAD

**Issue by lujinda** [cjxhaaa/duapp-sign#2]
https://github.com/cjxhaaa/duapp-sign/blob/20e284709bdf286ee8468875aa7d60decee972ed/sign/sign.go#L192

可以把JS逻辑来源的url或者源码贴出来，后续review方便点

**Comment by cjxhaaa** [comment]
已添加sign.js文件， 9160行开始即getSign函数逻辑 @lujinda
