### ISSUE TITLE
关于newSgin

### ISSUE THREAD

**Issue by zeng980520** [cjxhaaa/duapp-sign#3]
前辈，能指点下newSgin这个是如何生成的呢？您这个go的我看了，由于我没有学过看不懂。想问下有没有python版本的呢？

**Comment by cjxhaaa** [comment]
> 前辈，能指点下newSgin这个是如何生成的呢？您这个go的我看了，由于我没有学过看不懂。想问下有没有python版本的呢？
你说的newSgin应该是App接口的参数，这个没有，你可以试试用安卓反编译工具jeb尝试看看源代码。我这个版本的是只是h5页面的sign参数了

**Comment by cjxhaaa** [comment]
> 前辈，能指点下newSgin这个是如何生成的呢？您这个go的我看了，由于我没有学过看不懂。想问下有没有python版本的呢？

python版本的已经没有了，这个代码其实只是对sign.js各个加密函数的复现，而且这段代码得到的sign只是h5页面的签名参数，你说的newSign应该是App接口的签名参数，可以试试用安卓反编译工具jeb看看源码。
