### ISSUE TITLE
签名认证失败

### ISSUE THREAD

**Issue by youaremywind** [cjxhaaa/duapp-sign#4]
2020年3月28日 拿着要请求的参数去请求一下加密api 获取到和你一样的sign参数文本信息9ca955484240e758f7f5b876ec72fd74 然后去post请求返回
{
    "code": 401,
    "error": true,
    "msg": "签名认证失败!",
    "status": 401
}

**Comment by cjxhaaa** [comment]
> 2020年3月28日 拿着要请求的参数去请求一下加密api 获取到和你一样的sign参数文本信息9ca955484240e758f7f5b876ec72fd74 然后去post请求返回
> {
> "code": 401,
> "error": true,
> "msg": "签名认证失败!",
> "status": 401
> }

你可以试试用python的requests打个请求
`
import requests

resp = requests.post("https://app.poizon.com/api/v1/h5/index/fire/flow/product/detail",json={"spuId":"10242","productSourceName":"","propertyValueId":"","sign":"9ca955484240e758f7f5b876ec72fd74"})
`
我测试了是没有问题的

**Comment by cjxhaaa** [comment]
> 2020年3月28日 拿着要请求的参数去请求一下加密api 获取到和你一样的sign参数文本信息9ca955484240e758f7f5b876ec72fd74 然后去post请求返回
> {
> "code": 401,
> "error": true,
> "msg": "签名认证失败!",
> "status": 401
> }

已经更新了README请求实例，可以参考下
