### ISSUE TITLE
获取商品的时候怎么获取呢

### ISSUE THREAD

**Issue by UncAnnyZ** [cjxhaaa/duapp-sign#5]
https://app.poizon.com/api/v1/h5/index/fire/shopping-tab的时候
json_data = {"tabId":id,"limit":20,"lastId":""}
就获取不到sign了

**Comment by cjxhaaa** [comment]
> [https://app.poizon.com/api/v1/h5/index/fire/shopping-tab的时候](https://app.poizon.com/api/v1/h5/index/fire/shopping-tab%E7%9A%84%E6%97%B6%E5%80%99)
> json_data = {"tabId":id,"limit":20,"lastId":""}
> 就获取不到sign了

你试试请求http://localhost:9999/get_detail_sign?params={"tabId":id,"limit":"20","lastId":""}

注意下params里面的值都转成字符串丢进去再请求

拿到sign后拼进json_data中再向POST:https://app.poizon.com/api/v1/h5/index/fire/shopping-tab 

流程其实就是请求得到sign值，再向官方的接口请求

**Comment by UncAnnyZ** [comment]
我刚刚看了，他这个加密不仅仅要加这个，还需要一个标识，我刚刚看了另外一个python的，可以实现出来，但是标识好像只能反编译。

**Comment by cjxhaaa** [comment]
> 我刚刚看了，他这个加密不仅仅要加这个，还需要一个标识，我刚刚看了另外一个python的，可以实现出来，但是标识好像只能反编译。

你指的标识是什么？可以举个例子么

**Comment by UncAnnyZ** [comment]
文章地址：https://github.com/luo1994/du-app-sign
代码部分：sign = ctx.call('getSign','lastId{}limit20productId{}sourceAppapp19bc545a393a25177083d4a748807cc0'.format(lastId,productId))
问题：这里的“sourceAppapp”

**Comment by cjxhaaa** [comment]
> 文章地址：https://github.com/luo1994/du-app-sign
> 代码部分：sign = ctx.call('getSign','lastId{}limit20productId{}sourceAppapp19bc545a393a25177083d4a748807cc0'.format(lastId,productId))
> 问题：这里的“sourceAppapp”

可能是不同的接口吧，没看太明白。我测试了一个数据你可以试试
json_data = {"tabId":"4","limit":"20","lastId":""}
你调用http://localhost:9999/get_detail_sign?params={"tabId":"4","limit":"20","lastId":""}
可以得到d7344b0ac875de68adaef66b43c37843

最后post请求: https://app.poizon.com/api/v1/h5/index/fire/shopping-tab
json = {"tabId":"4","limit":"20","lastId":"","sign":"d7344b0ac875de68adaef66b43c37843"}
是可以得到数据的

这个程序是辅助得到加密参数的工具，至于具体爬什么内容具体分析吧

**Comment by UncAnnyZ** [comment]
行，我试一下看看，谢谢大哥

**Comment by UncAnnyZ** [comment]
import requests
headers = {
    'AppId': "wxapp",
    'Content-Type': 'application/json'
}
# spuId就是毒商品的特征id
json_data = {"spuld":"74067"}

sign_text = requests.get('http://localhost:5000/get_detail_sign?params={"spuld":"74067"}').text
print(sign_text)

json_data['sign']=sign_text

product_data = requests.post('https://app.poizon.com/api/v1/h5/inventory/price/h5/queryBuyNowInfo',json=json_data,headers=headers)
print(product_data.text)


我这里就就对不上sign了
